### ISSUE TITLE
Do you have plan to release current updates to crate.io?

### ISSUE THREAD

**Issue by giangndm** [paolobarbolini/rusty-s3#114]
My project relies on some features of rusty-s3 but they haven’t been published to crates.io yet. Do you have any plans to release a patch soon?

**Comment by paolobarbolini** [comment]
Sorry for the long wait. We're planning on merging #112 and #118 in the following days and then releasing a new version.

**Comment by paolobarbolini** [comment]
#112 has been merged. #118 is having some difficulties but it's not a requirement for the release. clippy is broken on the main branch Cc @guerinoni

**Comment by giangndm** [comment]
@paolobarbolini   Thank for letting me know. I hope it gets resolved soon.

**Comment by paolobarbolini** [comment]
Released as [v0.7.0](https://github.com/paolobarbolini/rusty-s3/releases/tag/v0.7.0)
