### ISSUE TITLE
Make `BucketError` public

### ISSUE THREAD

**Issue by ryanmcgrath** [paolobarbolini/rusty-s3#56]
Heya! Love the library.

Any reason `BucketError` isn't or can't be made public? Right now it's private and makes wrapping errors from the bucket `new` method a bit wonky.

**Comment by paolobarbolini** [comment]
We must have forgotten to re-export it. Could you send a PR to fix it?

**Comment by ryanmcgrath** [comment]
Done, will close this~

**Comment by paolobarbolini** [comment]
Released as 0.3.1

https://github.com/paolobarbolini/rusty-s3/releases/tag/v0.3.1

**Comment by ryanmcgrath** [comment]
Thanks!
