### ISSUE TITLE
Can we get a new release

### ISSUE THREAD

**Issue by irevoire** [paolobarbolini/rusty-s3#86]
Hello, do you think it would be possible to get a new release with all the latest changes?

**Comment by paolobarbolini** [comment]
I ended up forgetting to look at this over the weekend. I've merged #85 and left a comment in #82

**Comment by paolobarbolini** [comment]
Released as [v0.5.0](https://github.com/paolobarbolini/rusty-s3/releases/tag/v0.5.0)
